### ISSUE TITLE
Any plans to turn this into a generic driver?

### ISSUE THREAD

**Issue by therealprof** [smoltcp-rs/ENC424J600#1]
Hi there.

First of all great work, I've managed to this get this crate to work easily on my homebrewn ENC424J600 board.

Currently this is all very much dependent on `stm32f4xx-hal` (which is cool 😎) but it doesn't make for a great universal driver, even the `embedded-hal` trait is re-exported from there:

https://github.com/smoltcp-rs/ENC424J600/blob/b38c5ae65b5e907737aa2cbe61c22cfdec2dd04b/src/spi.rs#L2-L8

The `Cargo.toml` is lying, too, since `stm32f4xx-hal` is defacto not an `optional` dependency. Even just using it from another project which is based on a STM32F4 is not possible at the moment due to this. 😢 

Hence my question what the plans for the future are.

**Comment by HarryMakes** [comment]
@therealprof Thanks for the comment. Yes it is obvious that certain parts of my code should've been made generic to other HALs as well. I'm working on it now. :smile:

**Comment by HarryMakes** [comment]
7b313292cad420233bf8e53acf7591a65f3c3367 now has the driver library dependent on `embedded_hal` instead of `stm32f4xx_hal`, rendering dependencies on STM32F4xx HAL truly optional except for running the provided examples.

**Comment by therealprof** [comment]
Excellent, I hope I will find time later today to try it.

**Comment by therealprof** [comment]
Can't test whether it works at the moment but at least I can compile out-of-tree code with the driver. I guess we can consider this done. Thanks a lot! 👍
